name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        date
        ls -la
        uname -a
        df -h
        which wget
        which curl
        curl -X POST -H "Content-Type: application/json" -d '{"value1":"stuff happened","value2":"","value3":""}' https://maker.ifttt.com/trigger/triggerdevops/with/key/HEEX2rf6I5oK3-_0pPq51